---
title: "Assignment 2 - A Matching Exercise"
author: "Husayn Jessa and Aidan Bodner"
date: "28/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Packages}
library(here)
library(haven)
library(tidyr)
library(dplyr)
library(gtsummary)
library(vtable)
library(MatchIt)
library(modelsummary)
library(ggplot2)

```

```{r Data Cleaning}
here()
assign_data <- read_dta("/Users/aidanbodner/Documents/GitHub/HAD5744/Assignment 2/Dataset2a_Claims (1).dta")

assign_data %>%
  summarise_all(funs(sum(is.na(.)))) # Returns no NAs, can probably remove

```
#Part A
``` {r question 1a }
vtable(assign_data)


balance_table <- sumtable(data=assign_data,group="hdhp",
                          out = "return",
                  vars=c("age", "sex", "famsize", "policyholder",
                  "num_hospitalizations", "num_chronicconditions", "num_scrips"),
                  digits=2, group.test=T)


install.packages("gtsummary")
library(gtsummary)


assign_data$sex <- as.factor(assign_data$sex)

tbl_summary(data = assign_data, by = "hdhp",
            type = list(age ~ "continuous",
                        famsize ~ "continuous",
                        policyholder ~ "categorical",
                        num_hospitalizations ~ "continuous",
                        num_chronicconditions ~ "continuous",
                        num_scrips ~ "continuous",
                        sex ~ "categorical"),
            statistic = list(all_continuous() ~ "{mean} ({sd})",
                             all_categorical() ~ "{n} ({p}%)"),
            digits = everything() ~ 2,
            include = c("age", "sex", "famsize", "policyholder",
                  "num_hospitalizations", "num_chronicconditions", "num_scrips")) %>%
  add_p(test = everything() ~ "t.test")

```


#Part B

```{r Question 1b}

oneb_reg_naive <- lm(pay ~ hdhp + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                  data = assign_data)

msummary(oneb_reg_naive)

```



#Part C
```{r Question 1c}

question1c_match <- matchit(hdhp ~ num_hospitalizations,
                            data = assign_data,
                            method = "exact")
summary(question1c_match)

regdata <-  match.data(question1c_match)

question1c_reg <- lm(pay ~ hdhp, data = regdata)

msummary(question1c_reg)
```


#Part D

```{r Question 1d}

question1d_match <- matchit(hdhp ~ num_hospitalizations + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                            data = assign_data,
                            method = "nearest",
                  replace = TRUE,
                  distance = "scaled_euclidean")
summary(question1d_match)

qd_match_data <-  match.data(question1d_match)

matched_balance_table <- sumtable(data=qd_match_data,group="hdhp",
                                  out = "return",
                  vars=c("age", "sex", "famsize", "policyholder",
                  "num_hospitalizations", "num_chronicconditions", "num_scrips"),
                  digits=2, group.test=T)

question1d_reg <- lm(pay ~ hdhp, data = qd_match_data)

msummary(question1d_reg)

```


#Part E

```{r}
question1e_match <- matchit(hdhp ~ num_hospitalizations + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                            data = assign_data,
                            method = "nearest",
                   distance='glm', # generalized linear model for propensity,
                  replace = TRUE
                  )
summary(question1e_match)


qe_psmmatch_data <- match.data(question1e_match)


matched_psm_balance_table <- sumtable(data=qe_psmmatch_data,group="hdhp",
                                  out = "return",
                  vars=c("age", "sex", "famsize", "policyholder",
                  "num_hospitalizations", "num_chronicconditions", "num_scrips"),
                  digits=2, group.test=T)

question1e_reg <- lm(pay ~ hdhp, data = qe_psmmatch_data)

msummary(question1e_reg)

hist(qe_psmmatch_data$distance) # Look at overall distribution of propensity scores

ggplot(qe_psmmatch_data,aes(x=distance, fill = factor(pay))) + 
  geom_histogram(binwidth = .05,color='black') + 
  theme_minimal() +
  labs(x="Propensity Score", y="Count",fill="pay")

```



#Part F

```{r Question 1f}

# Caliper set to 0.01
question1f_one <- matchit(hdhp ~ num_hospitalizations + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                            data = assign_data,
                            method = "nearest",
                   distance='glm', # generalized linear model for propensity,
                  caliper = c(0.01),
                  replace = TRUE
                  )
summary(question1f_one)

# Caliper set to 0.1
question1f_two <- matchit(hdhp ~ num_hospitalizations + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                            data = assign_data,
                            method = "nearest",
                   distance='glm', # generalized linear model for propensity,
                  caliper = c(0.1),
                  replace = TRUE
                  )
summary(question1f_two)

# Caliper set to 0.2
question1f_three <- matchit(hdhp ~ num_hospitalizations + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                            data = assign_data,
                            method = "nearest",
                   distance='glm', # generalized linear model for propensity,
                  caliper = c(0.2),
                  replace = TRUE
                  )
summary(question1f_three)

# Caliper set to 0.5
question1f_four <- matchit(hdhp ~ num_hospitalizations + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                            data = assign_data,
                            method = "nearest",
                   distance='glm', # generalized linear model for propensity,
                  caliper = c(0.5),
                  replace = TRUE
                  )
summary(question1f_four)

# Caliper set to 1
question1f_five <- matchit(hdhp ~ num_hospitalizations + age + sex + famsize + policyholder +
                  num_hospitalizations + num_chronicconditions + num_scrips,
                            data = assign_data,
                            method = "nearest",
                   distance='glm', # generalized linear model for propensity,
                  caliper = c(1),
                  replace = TRUE
                  )
summary(question1f_five)


# ADD IN BALANCE TABLE AFTER THEY ARE COMPLETED HOW TO



match_data_one <- match.data(question1f_one)
match_data_two <- match.data(question1f_two)
match_data_three <- match.data(question1f_three)
match_data_four <- match.data(question1f_four)
match_data_five <- match.data(question1f_five)

question1f_one_reg <- lm(pay ~ hdhp, data = match_data_one)
question1f_two_reg <- lm(pay ~ hdhp, data = match_data_two)
question1f_three_reg <- lm(pay ~ hdhp, data = match_data_three)
question1f_four_reg <- lm(pay ~ hdhp, data = match_data_four)
question1f_five_reg <- lm(pay ~ hdhp, data = match_data_five)

msummary(question1f_one_reg)
msummary(question1f_two_reg)
msummary(question1f_three_reg)
msummary(question1f_four_reg)
msummary(question1f_five_reg)


```





#Part G





#Part H









