---
title: "Assignment 3"
author: "Husayn Jessa and Aidan Bodner"
date: "16/11/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages
```{r Packages}
library(here)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(ggrepel)
library(ggtext)
library(showtext)
library(stringr)
library(fastDummies)
```

# Data and Cleaning
```{r Data and Cleaning}
name <- Sys.info() 
name[7]

assign_data <- read.csv("a3_p1_sourdough_trends.csv")

```

# Question 1a
```{r Question 1a}

assign_data$date <- str_replace_all(assign_data$date, "T00:00:00Z", "")
assign_data$date <- as.factor(assign_data$date)
assign_data$date <- as.numeric(assign_data$date) #idk if we should do this

q1_line_graph <- ggplot(assign_data, (aes(x = date, y = hits, group = keyword))) + 
  geom_line(aes(color = keyword)) + theme_linedraw() + labs(x = "Date", y = "Hits") +
  geom_vline(xintercept = as.numeric(assign_data$date[75]), 
    color = "red") + geom_text(aes(x = as.numeric(date[120]), label="Start of Pandemic (2020-03-15)", y=90), color = "red") +
  scale_x_discrete(breaks = c("2020-01-01",
                              "2020-02-01",
                              "2020-03-01",
                              "2020-04-01",
                              "2020-05-01",
                              "2020-06-01",
                              "2020-07-01",
                              "2020-08-01"), labels = waiver())

q1_line_graph


#I wanted to make a line graph without converting our dates to numeric:
assign_data$date <- str_replace_all(assign_data$date, "T00:00:00Z", "")

hq1_line_graph <- ggplot(assign_data, aes(x = date, y = hits, colour = keyword, group = keyword)) +
                theme_classic()  + geom_vline(xintercept = assign_data$date[75], show.legend = FALSE) + annotate("text", x=assign_data$date[70], y=86, label="Start of Pandemic ", angle=90) + geom_line() +  scale_x_discrete(breaks = c("2020-01-01",
                              "2020-02-01",
                              "2020-03-01",
                              "2020-04-01",
                              "2020-05-01",
                              "2020-06-01",
                              "2020-07-01",
                              "2020-08-01")) + ggtitle("Interest in Food Types Over Time")

hq1_line_graph
```

# Question 1b
```{r Question 1b}

# Look at plots for each food individually, to gauge trend lines: 
sourdough_plot <- ggplot(assign_data[which(assign_data$keyword=="sourdough"),],aes(x=date,y=hits,group=keyword, colour = keyword)) + geom_line() +
  theme_classic() + labs(x="Time",y="Hits") + 
  geom_vline(xintercept = assign_data$date[75], show.legend = FALSE)  + annotate("text", x=assign_data$date[70], y=15, label="Start of Pandemic (2020-03-15)", angle=90) + geom_line() +scale_x_discrete(breaks = c("2020-01-01",
                              "2020-02-01",
                              "2020-03-01",
                              "2020-04-01",
                              "2020-05-01",
                              "2020-06-01",
                              "2020-07-01",
                              "2020-08-01"))

cereal_plot <- ggplot(assign_data[which(assign_data$keyword=="cereal"),],aes(x=date,y=hits,group=keyword, colour = keyword)) + geom_line() +
  theme_classic() + labs(x="Time",y="Hits") + 
  geom_vline(xintercept = assign_data$date[75], show.legend = FALSE)  + annotate("text", x=assign_data$date[70], y=15, label="Start of Pandemic (2020-03-15)", angle=90) + geom_line() +scale_x_discrete(breaks = c("2020-01-01",
                              "2020-02-01",
                              "2020-03-01",
                              "2020-04-01",
                              "2020-05-01",
                              "2020-06-01",
                              "2020-07-01",
                              "2020-08-01"))

sandwich_plot <- ggplot(assign_data[which(assign_data$keyword=="sandwich"),],aes(x=date,y=hits,group=keyword, colour = keyword)) + geom_line() +
  theme_classic() + labs(x="Time",y="Hits") + 
  geom_vline(xintercept = assign_data$date[75], show.legend = FALSE)  + annotate("text", x=assign_data$date[70], y=15, label="Start of Pandemic (2020-03-15)", angle=90) + geom_line() +scale_x_discrete(breaks = c("2020-01-01",
                              "2020-02-01",
                              "2020-03-01",
                              "2020-04-01",
                              "2020-05-01",
                              "2020-06-01",
                              "2020-07-01",
                              "2020-08-01"))
  
soup_plot <- ggplot(assign_data[which(assign_data$keyword=="soup"),],aes(x=date,y=hits,group=keyword, colour = keyword)) + geom_line() +
  theme_classic() + labs(x="Time",y="Hits") + 
  geom_vline(xintercept = assign_data$date[75], show.legend = FALSE)  + annotate("text", x=assign_data$date[70], y=15, label="Start of Pandemic (2020-03-15)", angle=90) + geom_line() +scale_x_discrete(breaks = c("2020-01-01",
                              "2020-02-01",
                              "2020-03-01",
                              "2020-04-01",
                              "2020-05-01",
                              "2020-06-01",
                              "2020-07-01",
                              "2020-08-01"))

cereal_plot
sandwich_plot
soup_plot
sourdough_plot




```

# Question 1c
```{r Question 1c}

```

# Question 1d
```{r Question 1d}

```




